version: '3.8'
services:
  # Servicio de base de datos para el microservicio de customer
  customer-db:
    image: mysql:8.0
    container_name: customer_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: customer_db
      MYSQL_USER: customer_user
      MYSQL_PASSWORD: customer_password
    ports:
      - "3308:3306"  # Expone el puerto 3308 para el microservicio de customer
    volumes:
      - customer_db_data:/var/lib/mysql

  # Microservicio de customer
  customer-service:
    build: .
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://customer-db:3306/customer_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: customer_user
      SPRING_DATASOURCE_PASSWORD: customer_password
    depends_on:
      - customer-db

volumes:
  customer_db_data: