version: '3.8'
services:
  customer-service:
    build: .
    ports:
      - "8082:8080"  # Expone el servicio en el puerto 8081 del host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/prueba-sofka?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq
      - mysql-db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      # Puerto para las comunicaciones de RabbitMQ
      - "15672:15672"    # Consola de administración de RabbitMQ

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prueba-sofka
    ports:
      - "3306:3306"  # Puerto de la base de datos MySQL